command! DevTest call vim_dev_ide#Test("buffer")
command! DevExec call vim_dev_ide#DevExec(expand('<cword>'))
command! DevCreateSnippet call vim_samplesnip_maker#CreateAliasAndSnippets(expand('<cword>'))
command! DevNaverDic call vim_naver_dic#GetNaverDic(expand('<cword>'))
command! DevNaverPapago call vim_naver_dic#GetNaverPapago(expand('<cword>'))
command! DevMoveNextSymbolForword call vim_dev_ide#MoveNextSymbol('forword')
command! DevMoveNextSymbolBackword call vim_dev_ide#MoveNextSymbol('backword')
