command! DevTest call vim_dev_ide#Test("buffer")
command! DevExec call vim_dev_ide#DevExec(expand('<cword>'))
command! DevCreateSnippet call vim_samplesnip_maker#CreateAliasAndSnippets(expand('<cword>'))
command! DevNaverDic call vim_naver_dic#GetNaverDic(expand('<cword>'))
command! DevNaverPapagoKor call vim_naver_dic#GetNaverPapago('ko')
command! DevNaverPapagoEng call vim_naver_dic#GetNaverPapago('en')
command! DevMoveNextSymbolForword call vim_dev_ide#MoveNextSymbol('forword')
command! DevMoveNextSymbolBackword call vim_dev_ide#MoveNextSymbol('backword')
